language: bash
services: docker
sudo: required

env:
  - VERSION=php/5.6/
  - VERSION=php/5.6/fpm/
  - VERSION=php/7.0/
  - VERSION=php/7.0/fpm/
  - VERSION=php/7.1/
  - VERSION=php/7.1/fpm/
  - VERSION=php/7.2/
  - VERSION=php/7.2/fpm/
  - VERSION=php/7.3/
  - VERSION=php/7.3/fpm/

before_script:
  - cd $VERSION

script:
  - docker build .

after_script:
  - docker images
